name: ubuntu_package_manager
description: "A new Flutter project."
publish_to: 'none'
version: 2026.04.04

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  signals: ^7.1.0
  signals_flutter: ^7.1.0
  file_selector: ^1.1.0
  flutter_svg: ^2.3.0
  flex_color_scheme: ^8.4.0
  contact_list_view: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  signals_lint: ^7.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/logo.png
